source 'https://rubygems.org'

gem 'rake'
gem 'motion-bundler'
gem 'motion-cocoapods'
gem 'motion-testflight'
#gem 'xcodeproj', '0.11.1'
gem 'xcodeproj'
#gem 'ib', '0.4.2'
gem 'ib', '0.4.7'
gem 'afmotion', '~> 2.1.0'
